apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailrpproxy
spec:
  statefulSet:
    annotations:
      reloader.stakater.com/auto: "false"
    pod:
      annotations:
        reloader.stakater.com/auto: "false"
      tailscaleContainer:
        image: ghcr.io/eseiker/tailrpproxy:latest
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: tailrpproxy
spec:
  proxyClass: tailrpproxy
  subnetRouter:
    advertiseRoutes:
      - 10.7.0.1/32
